//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ISIP123_Soldatov_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public int BalanceID { get; set; }
        private decimal _currentBalance;
        public decimal CurrentBalance
        {
            get => _currentBalance;
            set
            {
                if (value < 0)
                {
                    throw new ArgumentOutOfRangeException(nameof(CurrentBalance), "Текущий баланс не может быть отрицательным.");
                }
                _currentBalance = value;
            }
        }
        public System.DateTime LastUpdated { get; set; }
        public Balance(decimal initialBalance)
        {
            if (initialBalance < 0)
            {
                throw new ArgumentOutOfRangeException(nameof(initialBalance), "Начальный баланс не может быть отрицательным.");
            }

            CurrentBalance = initialBalance;
            LastUpdated = DateTime.Now;
        }

        public Balance() { }

        public void UpdateBalance(decimal amount)
        {
            CurrentBalance += amount;
            LastUpdated = DateTime.Now;
        }
    }
}