//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Soldatov_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerOrders()
        {
            this.Penalties = new HashSet<Penalties>();
        }
    
        public int OrderID { get; set; }
        public string CustomerName { get; set; }
        public int BrokenPartID { get; set; }
        public decimal RepairCost { get; set; }
        public string OrderStatus { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual PartsInventory PartsInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Penalties> Penalties { get; set; }
    }
}
