//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Soldatov_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartPurchases
    {
        public int PurchaseID { get; set; }
        public int PartID { get; set; }
        public int Quantity { get; set; }
        public decimal TotalCost { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    
        public virtual PartsInventory PartsInventory { get; set; }
    }
}
