//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ISIP123_Soldatov_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Part()
        {
            this.Purchase = new HashSet<Purchase>();
        }
    
        public int PartID { get; set; }
        private string _partName;
        public string PartName
        {
            get => _partName;
            set
            {
                if (string.IsNullOrWhiteSpace(value))
                {
                    throw new ArgumentException("Название детали не может быть пустым.");
                }
                _partName = value;
            }
        }
        private int _quantity;
        public int Quantity
        {
            get => _quantity;
            set
            {
                if (value < 0)
                {
                    throw new ArgumentOutOfRangeException(nameof(Quantity), "Количество не может быть отрицательным.");
                }
                _quantity = value;
            }
        }
        private decimal _buyPrice;
        public decimal BuyPrice
        { 
            get => _buyPrice;
            set 
            {
                if (value <= 0)
                {
                    throw new ArgumentOutOfRangeException(nameof(BuyPrice), "Стоимость за единицу должна быть положительной.");
                }
                _buyPrice = value;
            }
        }
        private decimal _repairPrice;
        public decimal RepairPrice
        { 
            get => _repairPrice;
            set 
            {
                if (value <= 0)
                {
                    throw new ArgumentOutOfRangeException(nameof(RepairPrice), "Общая стоимость должна быть положительной.");
                }
                _repairPrice = value;
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchase { get; set; }
        public Part(string partName, int quantity, decimal buyPrice, decimal repairPrice)
        {
            PartName = partName;
            Quantity = quantity;
            BuyPrice = buyPrice;
            RepairPrice = repairPrice;
        }
    }
}
