//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Soldatov_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartPurchases
    {
        public int PurchaseID { get; set; }
        public int PartID { get; set; }
        private int _quantity;
        public int Quantity
        {
            get => _quantity;
            set
            {
                if (value <= 0)
                {
                    throw new ArgumentOutOfRangeException(nameof(Quantity), "Количество закупки должно быть положительным.");
                }
                _quantity = value;
            }
        }

        private decimal _totalCost;
        public decimal TotalCost
        {
            get => _totalCost;
            set
            {
                if (value <= 0)
                {
                    throw new ArgumentOutOfRangeException(nameof(TotalCost), "Общая стоимость должна быть положительной.");
                }
                _totalCost = value;
            }
        }
        public System.DateTime PurchaseDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    
        public virtual PartsInventory PartsInventory { get; set; }
        public PartPurchases(int partID, int quantity, decimal totalCost, int deliveryDelayCars = 2)
        { 
            PartID = partID;
            Quantity = quantity;
            TotalCost = totalCost;
            PurchaseDate = DateTime.Now;
            DeliveryDate = DateTime.Now.AddDays(deliveryDelayCars * 0.1); ;
        }
        public PartPurchases() { }
        public void UpdateDeliveryDate(DateTime newDeliveryDate)
        {
            DeliveryDate = newDeliveryDate;
        }
    }
}
