//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Soldatov_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalties
    {
        public int PenaltyID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string PenaltyType { get; set; }
        public decimal PenaltyAmount { get; set; }
        public System.DateTime PenaltyDate { get; set; }
    
        public virtual CustomerOrders CustomerOrders { get; set; }
    }
}
