//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Soldatov_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int PurchaseID { get; set; }
        public int PlayerID { get; set; }
        public int PartID { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual Player Player { get; set; }

        public Purchase(int playerID, int partID) 
        {
            PlayerID = playerID;
            PartID = partID;
        }
    }
}
